### ISSUE TITLE
Error compiling for board Teensy 4.1.

### ISSUE THREAD

**Issue by jmodj** [ARTS37/SerialMenuCmd#1]
Arduino: 1.8.15 (Mac OS X), TD: 1.54, Board: "Teensy 4.1, Serial, 600 MHz, Faster, US English"

In file included from /Users/jmo/Documents/Arduino/libraries/SerialMenuCmd/examples/example1/example1.ino:53:0:
/Users/jmo/Documents/Arduino/libraries/SerialMenuCmd/src/SerialMenuCmd.h:78:28: error: section attribute not allowed for 'tMenuCmdTxt'
 typedef const char PROGMEM tMenuCmdTxt;
                            ^
Error compiling for board Teensy 4.1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

EDIT: I found that if I remove the PROGMEM it works. 
I also found that the teensy stores all constant strings in flash, but I'm not sure if it's  true for the teensy 4.1 or just the teensy 3.

**Comment by ARTS37** [comment]
I'm sorry jmodj, I had not checked my google mailbox for a few days. regarding your problem I have not encountered it. Currently I am using arduino and seeeduino xiao boards but have never used a teensy board. To guide you in your debug, the tMenuCmdTxt declaration consists of locating character strings in the program memory space, hence the const char PROGMEM declaration. However, perhaps in the case of teensy targets, the PROGMEM specification is not supported. If by chance you tried to remove the PROGMEM specification from the source code, it may work, but be careful, this will locate the strings in the RAM (at the risk of consuming all this resource).
good luck, ARTS37

P.S. Do not hesitate to send me your fixes, I will take care of integrating them into the source code, not forgetting to quote you.
